pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'experiments'

include 'blogsite'
include 'bcel'
include 'completeablefuture'
include 'distributedthreadpool'
include 'evolution'
include 'flowpublisher'
include 'hashlife'
include 'jneuro'
include 'javakotlinbridges'
def kotlinBytecodeModules = [
    'kotlindatasynthetic',
    'kotlindefaultargs',
    'kotlindelegation',
    'kotlininlinecapture',
    'kotlinmetadatareader',
    'kotlinpropertyrefs',
    'kotlinsamfuninterface',
    'kotlinsealedwhen',
    'kotlinsuspendstate',
    'kotlinvalueclassboxing'
]

kotlinBytecodeModules.each { moduleName ->
    include moduleName
    project(":$moduleName").projectDir = file("kotlin/$moduleName")
}
include 'lambdabytecode'
include 'observableconcurrenttree'
include 'orderedthreadpoolexecutor'
include 'picontroller'
include 'slickproject'
include 'soapserver'
include 'webaspect'
