#!/usr/bin/env python3
"""Build or verify JNeuro's small, reproducible CUDA driver-API resource bundle.

Build with the pinned nvidia/cuda:13.0.2-devel-ubuntu24.04 image. Verification needs
only Python; ordinary Java/Kotlin builds and end users do not need a CUDA toolkit.
"""

import argparse
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


MODULE = Path(__file__).resolve().parents[1]
SOURCE = MODULE / "src/main/cuda/train.cu"
RESOURCES = MODULE / "src/main/resources/com/lis/neuro/cuda"
TOOLKIT = "13.0.2"
NVCC_VERSION = "Cuda compilation tools, release 13.0, V13.0.88"
ARCHITECTURE = "compute_75"
FLAGS = ("--ptx", "--std=c++17", f"--gpu-architecture={ARCHITECTURE}",
         "--fmad=false", "--prec-div=true", "--prec-sqrt=true", "--ftz=false")
KERNELS = ("forward", "output_delta", "hidden_delta", "update", "gather", "small_train_fp64", "small_train_fp32", "search_train_fp64", "search_train_fp32",
           "forward_fp32", "output_delta_fp32", "hidden_delta_fp32", "update_fp32", "gather_fp32", "small_train_fp32_packed", "small_train_fp32_2_4_1", "small_train_fp32_2_8_8_8_1", "search_train_fp32_packed")


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_metadata():
    return {
        "kernel.abi": "4",
        "source.sha256": sha256(SOURCE),
        "builder.sha256": sha256(Path(__file__).resolve()),
        "cuda.toolkit": TOOLKIT,
        "cuda.architecture": ARCHITECTURE,
        "cuda.flags": " ".join(FLAGS),
    }


def read_properties(path):
    properties = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition("=")
        if not separator or key in properties:
            raise ValueError(f"Invalid or duplicate property in {path}: {key}")
        properties[key] = value
    return properties


def verify(directory):
    ptx = directory / "train.ptx"
    metadata = read_properties(directory / "train.properties")
    expected = source_metadata() | {"ptx.sha256": sha256(ptx)}
    for key, value in expected.items():
        if metadata.get(key) != value:
            raise ValueError(f"CUDA resource mismatch: {key}; regenerate with build_cuda.py build")
    if metadata.get("cuda.nvcc") != NVCC_VERSION:
        raise ValueError("Missing or unexpected CUDA 13.0.88 compiler provenance")
    code = ptx.read_text(encoding="utf-8")
    for kernel in KERNELS:
        if not re.search(r"\.visible\s+\.entry\s+" + kernel + r"\s*\(", code):
            raise ValueError(f"Missing CUDA kernel: {kernel}")
    if not re.search(r"(?m)^\s*\.target\s+sm_75\b", code):
        raise ValueError("CUDA PTX must target sm_75")


def compiler(nvcc):
    executable = shutil.which(nvcc)
    if executable is None:
        raise ValueError(f"Cannot find {nvcc}; build in nvidia/cuda:{TOOLKIT}-devel-ubuntu24.04")
    # The pinned official container does not ship version.json. Validate the
    # compiler executable itself; the workflow pins the complete toolkit image.
    details = subprocess.run([executable, "--version"], check=True, text=True, capture_output=True).stdout
    if NVCC_VERSION not in details.splitlines():
        raise ValueError("nvcc does not report the expected CUDA 13.0.88 compiler")
    return executable, NVCC_VERSION


def normalize_ptx(path):
    """Remove nvcc's incidental trailing whitespace without changing instructions."""
    lines = (line.rstrip(" \t") for line in path.read_text(encoding="utf-8").splitlines())
    path.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8", newline="\n")


def build(directory, nvcc):
    executable, version = compiler(nvcc)
    directory.mkdir(parents=True, exist_ok=True)
    ptx = directory / "train.ptx"
    # Stable working directory and input basename avoid machine-specific paths.
    subprocess.run([executable, *FLAGS, "--output-file", str(ptx), SOURCE.name],
                   cwd=SOURCE.parent, check=True)
    normalize_ptx(ptx)
    metadata = source_metadata() | {"cuda.nvcc": version, "ptx.sha256": sha256(ptx)}
    (directory / "train.properties").write_text(
        "# Generated by jneuro/tools/build_cuda.py; do not edit.\n" +
        "".join(f"{key}={metadata[key]}\n" for key in sorted(metadata)), encoding="utf-8", newline="\n")
    verify(directory)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("build", "verify"))
    parser.add_argument("--output-dir", type=Path, default=RESOURCES)
    parser.add_argument("--nvcc", default=os.environ.get("NVCC", "nvcc"))
    parser.add_argument("--check", action="store_true", help="regenerate and compare without changing packaged files")
    args = parser.parse_args()
    directory = args.output_dir.resolve()
    if args.command == "verify":
        if args.check:
            parser.error("--check belongs to the build command")
        verify(directory)
    else:
        # Keep incomplete output away from the checked-in resource bundle.
        with tempfile.TemporaryDirectory(prefix="jneuro-cuda-") as temporary:
            generated = Path(temporary)
            build(generated, args.nvcc)
            if args.check:
                verify(directory)
                for name in ("train.ptx", "train.properties"):
                    if (generated / name).read_bytes() != (directory / name).read_bytes():
                        raise ValueError(f"CUDA resource is not reproducible: {name}")
            else:
                directory.mkdir(parents=True, exist_ok=True)
                for name in ("train.ptx", "train.properties"):
                    shutil.copyfile(generated / name, directory / name)
    print(f"CUDA resources {args.command} passed: {directory}")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, subprocess.CalledProcessError) as failure:
        print(f"CUDA resource validation failed: {failure}", file=sys.stderr)
        sys.exit(1)
